//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUT
    {
        public string ABOUTS_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string IMAGE { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION_1 { get; set; }
        public string DESCRIPTION_2 { get; set; }
        public string DESCRIPTION_3 { get; set; }
        public string DESCRIPTION_4 { get; set; }
        public string DESCRIPTION_5 { get; set; }
    }
}
