//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS
    {
        public int ADS_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
        public string POSITION { get; set; }
        public decimal WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string IMAGE { get; set; }
        public string LINK { get; set; }
        public Nullable<int> IDX { get; set; }
    }
}
