//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENCy
    {
        public int AGENCY_ID { get; set; }
        public string REGION { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string URL { get; set; }
        public string IMAGE { get; set; }
    }
}
