//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIES_BY_SUPPLIER
    {
        public int CATEGORIES_BY_SUPPLIER_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string CATEGORY_NAME { get; set; }
    }
}
