//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIES_EXTRA
    {
        public int CATEGORY_EXTRA_ID { get; set; }
        public string CATEGORY_EXTRA_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int CATEGORY_ID { get; set; }
        public bool IS_ACTIVE { get; set; }
    }
}
