//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGES_UPLOAD
    {
        public int IMAGES_ID { get; set; }
        public string NAME { get; set; }
        public string URL { get; set; }
        public Nullable<int> NEWS_ID { get; set; }
    }
}
