//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int NEWS_ID { get; set; }
        public string TITLE { get; set; }
        public string CONTENT_1 { get; set; }
        public string CONTENT_2 { get; set; }
        public string CONTENT_3 { get; set; }
        public string IMAGE_1 { get; set; }
        public string IMAGE_2 { get; set; }
        public string IMAGE_3 { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> SUPPLIER_ID { get; set; }
        public Nullable<bool> IS_PROMOTION { get; set; }
    }
}
