//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_PROMOTION
    {
        public int NEWS_PROMOTION_ID { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CONTENT { get; set; }
        public string IMAGE { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_USER { get; set; }
    }
}
