//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAILS
    {
        public int ORDER_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public decimal EXTENDED_PRICE { get; set; }
        public int ORDER_DETAIL_ID { get; set; }
        public string UNIT { get; set; }
    }
}
