//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_STATUS
    {
        public int ORDER_STATUS_ID { get; set; }
        public string ORDER_STATUS_NAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
