//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_FILES
    {
        public int PRODUCT_FILE_ID { get; set; }
        public string FILE_1 { get; set; }
        public string FILE_2 { get; set; }
        public string FILE_3 { get; set; }
        public string FILE_4 { get; set; }
        public string FILE_5 { get; set; }
        public int PRODUCT_ID { get; set; }
    }
}
