//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPPER
    {
        public int SHIPPER_ID { get; set; }
        public string SHIPPER_NAME { get; set; }
        public string PHONE { get; set; }
    }
}
