//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGMCO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECHNOLOGy
    {
        public int TECHNOLOGY_ID { get; set; }
        public string TECHNOLOGY_NAME { get; set; }
        public string IMAGE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
